sudo: required
services:
  - docker

before_install: 
  - docker build -t atulkatiyardocker/docker-test:react-test -f ./client/Dockerfile.dev ./client/

script: 
  - docker run -e CI=true atulkatiyardocker/docker-test:react-test npm test -- --coverage

after_success:
  - docker build -t atulkatiyardocker/docker-test:multi-client ./client
  - docker build -t atulkatiyardocker/docker-test:multi-nginx ./nginx
  - docker build -t atulkatiyardocker/docker-test:multi-worker ./worker
  - docker build -t atulkatiyardocker/docker-test:multi-server ./server
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push atulkatiyardocker/docker-test:multi-client
  - docker push atulkatiyardocker/docker-test:multi-nginx
  - docker push atulkatiyardocker/docker-test:multi-worker
  - docker atulkatiyardocker/docker-test:multi-server

 